name: Cesium for Unity
on: [push]
jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0 # so that `git describe` works.
      - name: Set environment variables
        run: |
          $ENV:CESIUM_UNITY_VERSION=$(git describe)
          # Make these available to subsequent steps
          echo "CESIUM_UNITY_VERSION=${ENV:CESIUM_UNREAL_VERSION}" >> $ENV:GITHUB_ENV
      - name: Install Unity
        run: |
          choco install wget
          wget https://download.unity3d.com/download_unity/9e7d58001ecf/Windows64EditorInstaller/UnitySetup64-2021.3.13f1.exe
          .\UnitySetup64-2021.3.13f1.exe /S
