name: Cesium for Unity
on: [push]
jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0 # so that `git describe` works.
      - name: Install wget
        run: choco install wget --no-progress
      - name: Create SSH tunnel to Unity License Server
        run: |
          $ErrorView = 'NormalView'
          $ENV:UNITY_LICENSE_SERVER_SSH_KEY | Set-Content ~/unity-client-ssh-key
          echo "-i ~/unity-client-ssh-key -L 8080:localhost:8080 unity-client@ec2-44-204-244-196.compute-1.amazonaws.com -N"
          start -FilePath ssh -ArgumentList "-i ~/unity-client-ssh-key -L 8080:localhost:8080 unity-client@ec2-44-204-244-196.compute-1.amazonaws.com -N" -RedirectStandardOuput stdout.log -RedirectStandardError stderr.log
          mkdir -p $ENV:PROGRAMDATA/Unity/config
          '{"licensingServiceBaseUrl": "http://localhost:8080","enableEntitlementLicensing": true,"clientConnectTimeoutSec": 5,"clientHandshakeTimeoutSec": 10}' > $ENV:PROGRAMDATA/Unity/config/services-config.json
          sleep 5
          echo OUT!
          cat stdout.log
          echo ERR!
          cat stderror.log
          # ssh -i ~/dne -L 8080:localhost:8080 unity-client@ec2-44-204-244-196.compute-1.amazonaws.com -N
          # ssh -i ~/unity-client-ssh-key -L 8080:localhost:8080 unity-client@ec2-44-204-244-196.compute-1.amazonaws.com -N
          wget http://127.0.0.1:8080/v1/admin/status
          cat status
      - name: Download Unity
        run: wget --quiet https://download.unity3d.com/download_unity/9e7d58001ecf/Windows64EditorInstaller/UnitySetup64-2021.3.13f1.exe
      - name: Test License Server
        run: |
          wget http://127.0.0.1:8080/v1/admin/status
          cat status
      - name: Install Unity
        run: start -FilePath ./UnitySetup64-2021.3.13f1.exe -ArgumentList "/S /D=C:\Program Files\Unity\Hub\Editor\2021.3.13f1" -wait
      - name: Delete Unity Installer
        run: rm ./UnitySetup64-2021.3.13f1.exe
      # - name: Download Unity Android Support
      #   run: wget --quiet https://download.unity3d.com/download_unity/9e7d58001ecf/TargetSupportInstaller/UnitySetup-Android-Support-for-Editor-2021.3.13f1.exe
      # - name: Install Unity Android Support
      #   run: start -FilePath ./UnitySetup-Android-Support-for-Editor-2021.3.13f1.exe -ArgumentList "/S /D=C:\Program Files\Unity\Hub\Editor\2021.3.13f1" -wait
      # - name: Delete Unity Android Support Installer
      #   run: rm ./UnitySetup-Android-Support-for-Editor-2021.3.13f1.exe
      - name: Create Empty Project
        run: |
          $ENV:UNITY="C:\Program Files\Unity\Hub\Editor\2021.3.13f1\Editor\Unity.exe"
          mkdir c:\cesium
          start -FilePath $ENV:UNITY -ArgumentList "-batchmode -quit -createProject c:\cesium\CesiumForUnityBuildProject -logFile c:\cesium\unity.log" -wait
          cat c:\cesium\unity.log
      - name: Move cesium-unity Repo Under Project
        run: |
          cd c:\cesium\CesiumForUnityBuildProject\Packages
          mv $ENV:GITHUB_WORKSPACE ./com.cesium.unity
      - name: Build Reinterop
        run: |
          c:\cesium\CesiumForUnityBuildProject\Packages\com.cesium.unity
          dotnet publish Reinterop~ -o .
      - name: Build Package
        run: |
          c:\cesium\CesiumForUnityBuildProject\Packages\com.cesium.unity
          dotnet run --project Build~
